#!/usr/bin/env python3
"""Generate the Nordic-branded launcher icon: adaptive vector layers + legacy raster mipmaps.

One geometry drives both outputs so the vector and the pre-API-26 rasters cannot drift apart.

Design: the Thingy:52's squircle case with its round button, emitting symmetrically to left and
right. Symmetric arcs are deliberate — a one-directional fan reads as the Wi-Fi glyph, which was
the rejected first concept. The Bluetooth rune was also rejected: it collides with system settings
UI, and the figuremark is a Bluetooth SIG trademark with brand rules restricting app-icon use.

Adaptive-icon geometry: 108dp viewport, only the centre 72dp is guaranteed visible, and the centre
66dp is the safe zone. All content here stays inside radius ~31 of centre (54,54).
"""
import math
import os

from PIL import Image, ImageDraw

RES = "/Users/armstrongllc/Desktop/BLE/nRFThingy52Android/app/src/main/res"

NORDIC_BLUE = "#00B7D7"   # NordicColors.nordicBlue
NORDIC_LAKE = "#008CD2"   # NordicColors.nordicLake

CENTER = 54.0
DEVICE_MIN, DEVICE_MAX, DEVICE_RADIUS = 40.0, 68.0, 9.0
BUTTON_RADIUS = 6.0
ARC_RADII = (21.0, 28.5)
ARC_STROKE = 5.0
ARC_HALF_ANGLE = 33.0  # degrees either side of horizontal

S = 108 * 8  # supersample factor for the raster pass


# ---------------------------------------------------------------- vector output

def arc_endpoints(r, left):
    """Screen-space (y-down) endpoints of one emission arc, ordered for an SVG sweep-flag of 1.

    Order matters and is not symmetric. An elliptical-arc command has four candidate arcs for a
    given endpoint pair and radius (two centres x two directions); the large-arc and sweep flags
    select one. Emitting the left arc with the same top-to-bottom ordering as the right one selects
    the arc centred at (18.78, 54) — bulging *right*, overlapping the device — rather than the
    intended mirror centred at (54, 54). Reversing the endpoint order for the left side keeps
    sweep=1 selecting the correct centre.
    """
    c, s = math.cos(math.radians(ARC_HALF_ANGLE)), math.sin(math.radians(ARC_HALF_ANGLE))
    dx = -r * c if left else r * c
    top, bottom = (CENTER + dx, CENTER - r * s), (CENTER + dx, CENTER + r * s)
    return (bottom, top) if left else (top, bottom)


def foreground_xml():
    lo, hi, r = DEVICE_MIN, DEVICE_MAX, DEVICE_RADIUS
    # Device body with the button punched out via evenOdd.
    body = (
        f"M{lo + r},{lo} L{hi - r},{lo} A{r},{r} 0 0 1 {hi},{lo + r} "
        f"L{hi},{hi - r} A{r},{r} 0 0 1 {hi - r},{hi} "
        f"L{lo + r},{hi} A{r},{r} 0 0 1 {lo},{hi - r} "
        f"L{lo},{lo + r} A{r},{r} 0 0 1 {lo + r},{lo} Z"
    )
    b = BUTTON_RADIUS
    button = (
        f"M{CENTER},{CENTER - b} A{b},{b} 0 1 0 {CENTER},{CENTER + b} "
        f"A{b},{b} 0 1 0 {CENTER},{CENTER - b} Z"
    )

    arcs = []
    for radius in ARC_RADII:
        for left in (False, True):
            (x0, y0), (x1, y1) = arc_endpoints(radius, left)
            # sweep=1: increasing angle is clockwise in y-down screen space.
            arcs.append(
                f'    <path\n'
                f'        android:pathData="M{x0:.2f},{y0:.2f} '
                f'A{radius},{radius} 0 0 1 {x1:.2f},{y1:.2f}"\n'
                f'        android:strokeColor="#FFFFFF"\n'
                f'        android:strokeWidth="{ARC_STROKE}"\n'
                f'        android:strokeLineCap="round" />'
            )

    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Launcher icon foreground: the Thingy:52's squircle case with its round button, emitting
     symmetrically. Symmetric arcs are deliberate — a one-directional fan reads as the Wi-Fi glyph.
     Generated by tools/gen_launcher_icon.py; edit the geometry there, not here.

     All content stays within the adaptive-icon safe zone (the centre 66dp of the 108dp viewport),
     so no mask shape clips it. Also serves as the `monochrome` layer: the system tints the alpha,
     and the button reads as a hole because the body path uses evenOdd. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FFFFFF"
        android:fillType="evenOdd"
        android:pathData="{body} {button}" />
{chr(10).join(arcs)}
</vector>
"""


def background_xml():
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Launcher icon background: the Nordic brand gradient, nordicBlue -> nordicLake. Both values are
     from NordicColors (ui/theme/Color.kt), ported from the iOS UIColorExtension.
     Generated by tools/gen_launcher_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr xmlns:aapt="http://schemas.android.com/aapt" name="android:fillColor">
            <gradient
                android:startX="54" android:startY="0"
                android:endX="54" android:endY="108"
                android:type="linear">
                <item android:offset="0" android:color="{NORDIC_BLUE}" />
                <item android:offset="1" android:color="{NORDIC_LAKE}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
"""


# ---------------------------------------------------------------- raster output

def u(v):
    return v * S / 108.0


def hex_rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5))


def render_full():
    """The complete 108dp icon at supersampled resolution."""
    img = Image.new("RGBA", (S, S))
    d = ImageDraw.Draw(img)
    a, b = hex_rgb(NORDIC_BLUE), hex_rgb(NORDIC_LAKE)
    for y in range(S):
        t = y / (S - 1)
        d.line([(0, y), (S, y)],
               fill=tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3)) + (255,))

    fg = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    fd = ImageDraw.Draw(fg)
    fd.rounded_rectangle([u(DEVICE_MIN), u(DEVICE_MIN), u(DEVICE_MAX), u(DEVICE_MAX)],
                         radius=u(DEVICE_RADIUS), fill=(255, 255, 255, 255))
    fd.ellipse([u(CENTER - BUTTON_RADIUS), u(CENTER - BUTTON_RADIUS),
                u(CENTER + BUTTON_RADIUS), u(CENTER + BUTTON_RADIUS)], fill=(0, 0, 0, 0))
    for radius in ARC_RADII:
        rr, w = u(radius), u(ARC_STROKE)
        box = [u(CENTER) - rr, u(CENTER) - rr, u(CENTER) + rr, u(CENTER) + rr]
        fd.arc(box, start=-ARC_HALF_ANGLE, end=ARC_HALF_ANGLE,
               fill=(255, 255, 255, 255), width=int(w))
        fd.arc(box, start=180 - ARC_HALF_ANGLE, end=180 + ARC_HALF_ANGLE,
               fill=(255, 255, 255, 255), width=int(w))
    img.alpha_composite(fg)
    return img


def legacy(full, size, round_shape):
    """Pre-API-26 icons get no system mask, so they carry their own shape.

    Crop to the 72dp visible window first: a legacy icon that included the full 108dp bleed would
    render the artwork noticeably smaller than every other app's.
    """
    win = full.crop((int(u(18)), int(u(18)), int(u(90)), int(u(90))))
    n = win.size[0]
    mask = Image.new("L", (n, n), 0)
    md = ImageDraw.Draw(mask)
    if round_shape:
        md.ellipse([0, 0, n - 1, n - 1], fill=255)
    else:
        md.rounded_rectangle([0, 0, n - 1, n - 1], radius=int(n * 0.22), fill=255)
    win = win.copy()
    win.putalpha(mask)
    return win.resize((size, size), Image.LANCZOS)


DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}


def main():
    with open(os.path.join(RES, "drawable", "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground_xml())
    with open(os.path.join(RES, "drawable", "ic_launcher_background.xml"), "w") as f:
        f.write(background_xml())
    print("wrote drawable/ic_launcher_{foreground,background}.xml")

    full = render_full()
    for density, size in DENSITIES.items():
        outdir = os.path.join(RES, f"mipmap-{density}")
        os.makedirs(outdir, exist_ok=True)
        for name, is_round in (("ic_launcher", False), ("ic_launcher_round", True)):
            img = legacy(full, size, is_round)
            img.save(os.path.join(outdir, f"{name}.webp"), "WEBP", lossless=True, quality=100)
        print(f"wrote mipmap-{density}/ic_launcher{{,_round}}.webp  {size}px")

    # A preview strip for eyeballing, not part of the build.
    prev = "/private/tmp/claude-501/-Users-armstrongllc-Desktop-BLE-nRFThingy52Android/d8249658-2d20-4f8c-8e90-3bbdbfaceabf/scratchpad/launcher_final.png"
    circ = Image.new("L", (S, S), 0)
    ImageDraw.Draw(circ).ellipse([u(18), u(18), u(90), u(90)], fill=255)
    sq = Image.new("L", (S, S), 0)
    ImageDraw.Draw(sq).rounded_rectangle([u(18), u(18), u(90), u(90)], radius=u(22), fill=255)
    out = Image.new("RGBA", (2 * 300 + 3 * 200 + 60, 320), (32, 32, 32, 255))
    x = 10
    for m in (circ, sq):
        v = full.copy()
        v.putalpha(m)
        out.alpha_composite(v.resize((300, 300), Image.LANCZOS), (x, 10))
        x += 310
    for density in ("mdpi", "hdpi", "xhdpi"):
        size = DENSITIES[density]
        img = legacy(full, size, False).resize((size, size), Image.LANCZOS)
        out.alpha_composite(img, (x, 20))
        x += size + 20
    out.convert("RGB").save(prev)
    print("preview:", prev)


if __name__ == "__main__":
    main()
